version: 2
before:
  hooks:
    - go mod tidy -v
builds:
  - ldflags:
      - -s -w
      - -X github.com/cnprobe/nezha/service/singleton.Version={{.Version}}
      - -extldflags "-static -fpic"
    flags:
      - -trimpath
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
snapshot:
  version_template: "dashboard"
