services:
  dashboard:
    image: nz_image_url
    container_name: nezha-dashboard
    restart: always
    volumes:
      - ./data:/dashboard/data
      - ./resource:/dashboard/resource:ro
    ports:
      - nz_site_port:80
      - nz_grpc_port:nz_grpc_port
